package com.lemicare.payment.service.dto.response;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO representing the response sent after successfully creating a Razorpay order.
 * This object contains all the necessary information for the frontend to initialize
 * the Razorpay Checkout SDK.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class CreateOrderResponse {

    /**
     * The unique order ID generated by Razorpay (e.g., "order_9A33XWu170gUtm").
     * This is the primary identifier for the transaction on Razorpay's side.
     */
    private String razorpayOrderId;

    /**
     * Your public Razorpay Key ID (e.g., "rzp_test_xxxxxxxxxxxxxx").
     * This is required by the frontend SDK to identify your merchant account.
     */
    private String razorpayKeyId;

    /**
     * The amount of the order in the primary currency unit (e.g., 1500.00 for INR).
     * The frontend displays this to the user for confirmation.
     */
    private double amount;

    /**
     * The name of your business or clinic, to be displayed on the Razorpay checkout modal.
     */
    private String merchantName;
}
