package com.lemicare.payment.service.dto.request;

import jakarta.validation.constraints.NotBlank;
import lombok.Data;

/**
 * DTO for the request body of the payment verification endpoint.
 * It contains the three critical pieces of information returned by the
 * Razorpay SDK to the client after a successful payment.
 */
@Data
public class VerifySignatureRequest {

    /**
     * The unique Order ID from Razorpay that was used to initiate the payment.
     */
    @NotBlank(message = "Razorpay Order ID is required.")
    private String razorpayOrderId;

    /**
     * The unique Payment ID generated by Razorpay for this specific successful transaction.
     */
    @NotBlank(message = "Razorpay Payment ID is required.")
    private String razorpayPaymentId;

    /**
     * The HMAC-SHA256 signature generated by Razorpay. The backend must
     * re-calculate this signature to verify the authenticity of the payment.
     */
    @NotBlank(message = "Razorpay signature is required.")
    private String razorpaySignature;
}
